const translations = {
    ar: {
        flag: "🇸🇦",
        name: "العربية",
        dir: "rtl",
        // الصفحة الرئيسية
        welcome: "X-PAY برو",
        mining_power: "طاقة التعدين الحالية",
        claim: "جمع الأرباح",
        games_title: "🎮 استثمر وقتك",
        luck_wheel: "عجلة الحظ",
        quiz_game: "تحدي الذكاء",
        wallet: "المحفظة المركزية",
        language_label: "اللغة",
        game_pts: "نقاط الألعاب",
        mine_pts: "حصيلة التعدين",
        convert: "تحويل النقاط 🔄",
        edit_profile: "تعديل الملف الشخصي",
        store: "المتجر",
        support: "الدعم الفني",
        watch_video: "شاهد فيديو (10+ نقاط)",
        latest_news: "آخر الأخبار:",
        // صفحة المتصدرين والإعلانات
        top_100: "أقوى 100 مستثمر 🚀",
        weekly_comp: "المنافسة الأسبوعية",
        daily: "يومي",
        weekly: "أسبوعي",
        monthly: "شهري",
        legend: "الأسطورة",
        you: "أنت",
        home: "الرئيسية",
        play_earn: "إلعب واكسب",
        watch_ad: "+10 نقاط",
        remaining: "متبقي",
        // النشاطات المباشرة
        live_active: "مستخدم نشط الآن",
        live_mining: "جاري تعدين XPC في هذه اللحظة..."
    },
    en: {
        flag: "🇺🇸",
        name: "English",
        dir: "ltr",
        welcome: "X-PAY PRO",
        mining_power: "Current Mining Power",
        claim: "Claim Rewards",
        games_title: "🎮 Invest Your Time",
        luck_wheel: "Lucky Wheel",
        quiz_game: "IQ Challenge",
        wallet: "Central Wallet",
        language_label: "Language",
        game_pts: "Game Points",
        mine_pts: "Mining Total",
        convert: "Convert Points 🔄",
        edit_profile: "Edit Profile",
        store: "Store",
        support: "Support",
        watch_video: "Watch Video (+10 pts)",
        latest_news: "Latest News:",
        top_100: "Top 100 Investors 🚀",
        weekly_comp: "Weekly Competition",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        legend: "Legend",
        you: "You",
        home: "Home",
        play_earn: "Play & Earn",
        watch_ad: "+10 Points",
        remaining: "left",
        live_active: "active users now",
        live_mining: "XPC being mined right now..."
    },
    fr: {
        flag: "🇫🇷",
        name: "Français",
        dir: "ltr",
        welcome: "X-PAY PRO",
        mining_power: "Puissance de Minage",
        claim: "Récupérer",
        games_title: "🎮 Investissez Votre Temps",
        luck_wheel: "Roue de la Fortune",
        quiz_game: "Défi IQ",
        wallet: "Portefeuille Central",
        language_label: "Langue",
        game_pts: "Points de Jeu",
        mine_pts: "Total Minage",
        convert: "Convertir 🔄",
        edit_profile: "Modifier Profil",
        store: "Boutique",
        support: "Support Technique",
        watch_video: "Regarder Vidéo (+10)",
        latest_news: "Dernières Nouvelles:",
        top_100: "Top 100 Investisseurs 🚀",
        weekly_comp: "Compétition Hebdomadaire",
        daily: "Quotidien",
        weekly: "Hebdomadaire",
        monthly: "Mensuel",
        legend: "Légende",
        you: "Vous",
        home: "Accueil",
        play_earn: "Jouer et Gagner",
        watch_ad: "+10 Points",
        remaining: "restant",
        live_active: "utilisateurs actifs",
        live_mining: "XPC en cours de minage..."
    },
    es: {
        flag: "🇪🇸",
        name: "Español",
        dir: "ltr",
        welcome: "X-PAY PRO",
        mining_power: "Poder de Minería",
        claim: "Reclamar",
        games_title: "🎮 Invierte tu Tiempo",
        luck_wheel: "Rueda de la Suerte",
        quiz_game: "Desafío IQ",
        wallet: "Billetera Central",
        language_label: "Idioma",
        game_pts: "Puntos de Juego",
        mine_pts: "Total Minería",
        convert: "Convertir 🔄",
        edit_profile: "Editar Perfil",
        store: "Tienda",
        support: "Soporte",
        watch_video: "Ver Video (+10 pts)",
        latest_news: "Últimas Noticias:",
        top_100: "Top 100 Inversores 🚀",
        weekly_comp: "Competición Semanal",
        daily: "Diario",
        weekly: "Semanal",
        monthly: "Mensual",
        legend: "Leyenda",
        you: "Tú",
        home: "Inicio",
        play_earn: "Jugar y Ganar",
        watch_ad: "+10 Puntos",
        remaining: "restante",
        live_active: "usuarios activos",
        live_mining: "XPC siendo minado ahora..."
    },
    zh: {
        flag: "🇨🇳",
        name: "中文",
        dir: "ltr",
        welcome: "X-PAY 专业版",
        mining_power: "当前挖矿能力",
        claim: "领取奖励",
        games_title: "🎮 投入你的时间",
        luck_wheel: "幸运轮盘",
        quiz_game: "智力挑战",
        wallet: "中央钱包",
        language_label: "语言",
        game_pts: "游戏积分",
        mine_pts: "挖矿总量",
        convert: "转换积分 🔄",
        edit_profile: "编辑个人资料",
        store: "商店",
        support: "技术支持",
        watch_video: "观看视频 (+10 分)",
        latest_news: "最新消息:",
        top_100: "前100名投资者 🚀",
        weekly_comp: "每周竞赛",
        daily: "每日",
        weekly: "每周",
        monthly: "每月",
        legend: "传奇",
        you: "你",
        home: "首页",
        play_earn: "玩游戏赚钱",
        watch_ad: "+10 积分",
        remaining: "剩余",
        live_active: "活跃用户",
        live_mining: "XPC 正在开采中..."
    },
    ru: {
        flag: "🇷🇺",
        name: "Русский",
        dir: "ltr",
        welcome: "X-PAY ПРО",
        mining_power: "Мощность майнинга",
        claim: "Получить",
        games_title: "🎮 Инвестируй время",
        luck_wheel: "Колесо удачи",
        quiz_game: "IQ Вызов",
        wallet: "Центральный кошелек",
        language_label: "Язык",
        game_pts: "Игровые очки",
        mine_pts: "Всего добыто",
        convert: "Конвертировать 🔄",
        edit_profile: "Профиль",
        store: "Магазин",
        support: "Поддержка",
        watch_video: "Смотреть (+10)",
        latest_news: "Последние новости:",
        top_100: "Топ 100 Инвесторов 🚀",
        weekly_comp: "Еженедельный конкурс",
        daily: "День",
        weekly: "Неделя",
        monthly: "Месяц",
        legend: "Легенда",
        you: "Вы",
        home: "Главная",
        play_earn: "Играй и зарабатывай",
        watch_ad: "+10 очков",
        remaining: "осталось",
        live_active: "активных пользователей",
        live_mining: "XPC добывается сейчас..."
    },
    hi: {
        flag: "🇮🇳",
        name: "हिन्दी",
        dir: "ltr",
        welcome: "X-PAY प्रो",
        mining_power: "खनन शक्ति",
        claim: "पुरस्कार प्राप्त करें",
        games_title: "🎮 अपना समय निवेश करें",
        luck_wheel: "भाग्य का पहिया",
        quiz_game: "आईक्यू चुनौती",
        wallet: "केंद्रीय वॉलेट",
        language_label: "भाषा",
        game_pts: "गेम अंक",
        mine_pts: "कुल खनन",
        convert: "अंक बदलें 🔄",
        edit_profile: "प्रोफ़ाइल संपादित करें",
        store: "स्टोर",
        support: "सहायता",
        watch_video: "वीडियो देखें (+10 अंक)",
        latest_news: "ताजा खबर:",
        top_100: "शीर्ष 100 निवेशक 🚀",
        weekly_comp: "साप्ताहिक प्रतियोगिता",
        daily: "दैनिक",
        weekly: "साप्ताहिक",
        monthly: "मासिक",
        legend: "दिग्गज",
        you: "आप",
        home: "होम",
        play_earn: "खेलें और कमाएं",
        watch_ad: "+10 अंक",
        remaining: "शेष",
        live_active: "सक्रिय उपयोगकर्ता",
        live_mining: "XPC अभी माइन किया जा रहा है..."
    }
};
